### ISSUE TITLE
Process exited before completing request - TypeError: Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by yahim91** [alexa/skill-sample-nodejs-highlowgame#1]
Hello,

I'm trying to set up a lambda using this framework but I receive the next error when testing:

TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:102:38)
    at AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:91:31)
    at exports.handler (/var/task/index.js:11:11)

I saw a few encountered this error, but no one gave a solution? Is there any fix for this?

**Comment by jasontvu** [comment]
I got same problem.

**Comment by brancusi** [comment]
Same here, even adding full admin permissions doesn't fix. Any ideas?

**Comment by ndedic** [comment]
When testing lambda, how does the json payload (test event) look like? It has to include 'locale' property, you can obtain proper request json by using Alexa simulator - it will generate one for you based on input text. Use that and configure a new lambda test event and try again. Also, if you're using lambda-local you can use the same payload to test the response. It should work.

**Comment by curtastic** [comment]
Your test json needs to be something like this. How do you get this? I don't know, I copied it from another skill that worked.

{
  "session": {
    "new": true,
    "sessionId": "SessionId.STUFF",
    "application": {
      "applicationId": "amzn1.ask.skill.STUFF"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.STUFF"
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.STUFF",
    "intent": {
      "name": "myIntent",
      "slots": {}
    },
    "locale": "en-US",
    "timestamp": "2017-10-13T20:48:50Z"
  },
  "context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.STUFF"
      },
      "user": {
        "userId": "amzn1.ask.account.STUFF"
      },
      "device": {
        "supportedInterfaces": {}
      }
    }
  },
  "version": "1.0"
}

**Comment by transce080** [comment]
Thank you, that JSON snippet was incredibly helpful.

**Comment by franklin-lobb** [comment]
Looks like the correct event example helped.  This issue has been closed due to inactivity.  If the issue still persists, please open a new issue.
