### ISSUE TITLE
Tutorial not consistent with new folder structure

### ISSUE THREAD

**Issue by Griffinx** [alexa/skill-sample-nodejs-highlowgame#11]
The new directory structure has messed up this tutorial

https://developer.amazon.com/blogs/post/tx24z2qzp5rrtg1/new-alexa-technical-tutorial-debugging-aws-lambda-code-locally

**Comment by davidhenley** [comment]
Also, you cannot use the Skill Builder with the NoIntent and the YesIntent

**Comment by johngo7470** [comment]
Agreed... 

https://github.com/alexa/skill-sample-nodejs-highlowgame (base website)

     has a "Get Started" link, which leads to:

https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/instructions/0-intro.md

     which is a bad link but scraping off 0-intro.md from the address:

https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/instructions re-directs to:

(note 'blob' is changed to 'tree' in the URL)

https://github.com/alexa/skill-sample-nodejs-highlowgame/tree/master/instructions

     where there is a link to 0-instructions.md:

https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/instructions/0-instructions.md 

(note tree has been changed back to blob)

which contains a "Get Started" link which points to:

https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/instructions/1-voice-user-interface.md

Admittedly confused where I should be getting started... 

Is the 'tree' version of the path correct? the 'blob' version?

**Comment by akersh-s** [comment]
Fixed in PR #24 . Closing this issue.
