### ISSUE TITLE
simulation fails at launch

### ISSUE THREAD

**Issue by zebralight** [alexa/skill-sample-nodejs-highlowgame#19]
```
"request": {
            "type": "LaunchRequest",
            "requestId": "amzn1.echo-api.request.etc",
            "timestamp": "2017-12-27T23:41:53Z",
            "locale": "en-US"
          }
```
I get an error "request to skill endpoint resulted in an error".  Could this be due to the lambda function missing an implemenation of the LaunchRequest handler?

**Comment by TianTXie** [comment]
I think it is because the execution role in lambda function does not include dynamoDB role.
Could you log into the aws website, go the ask-custom-highlow-default function, in the Execution role, add service-role/dynamoDB, and try to test again.

**Comment by mbrookes** [comment]
I added the 'AmazonDynamoDBFullAccess' policy to the ask-lambda-High-Low-Game role. Would be nice if the provided examples worked without all the hoop jumping. 🤕

**Comment by error404notfound** [comment]
thank you @mbrookes I had just finished sorting out the AWS credentials when I saw your post #27 and it brought me here, saving me alot of time.. it is frustrating that alot of these code samples arn't quite right, but I suppose as more people use them they will get streamlined 

My question is I go to add the execution role on lamda and there isn't a service-role/dynamoDB  infact I can't see service-role as an option. any suggestions. 

thank you for your time

**Comment by franklin-lobb** [comment]
Looks like the added policy may have solved the issue.  If not please reopen the issue.

**Comment by mbrookes** [comment]
@franklin-lobb what do you mean by "added policy"?

**Comment by franklin-lobb** [comment]
I meant that adding the AmazonDynamoDBFullAccess policy to the Lambda role.

**Comment by mbrookes** [comment]
But until that step is added to the tutorial for this sample, this issue isn't resolved.

**Comment by franklin-lobb** [comment]
Fair point.  It's been added to the main readme steps.  The other pages are still be updated.
