### ISSUE TITLE
unable to build with InteractionModel.json or models/en-US.json

### ISSUE THREAD

**Issue by johngo7470** [alexa/skill-sample-nodejs-highlowgame#28]
I followed the instructions to build this skill using the Alexa Skills Kit Developer Console Beta (following the latest instructions here at Github, updated 2/15/18), but I was unable to build using the top level InteractionModel.json, nor the models/en-US.json source.   When I tried to save either of them, I received an InvalidModelDefinitionSchema error.

I manually created the following json, which worked: (entered in JSON Editor)

{
    "languageModel": {
        "invocationName": "high low game",
        "intents": [
            {
                "name": "AMAZON.CancelIntent",
                "slots": [],
                "samples": []
            },
            {
                "name": "AMAZON.HelpIntent",
                "slots": [],
                "samples": []
            },
            {
                "name": "AMAZON.NoIntent",
                "slots": [],
                "samples": []
            },
            {
                "name": "AMAZON.StopIntent",
                "slots": [],
                "samples": []
            },
            {
                "name": "AMAZON.YesIntent",
                "slots": [],
                "samples": []
            },
            {
                "name": "NumberGuessIntent",
                "slots": [
                    {
                        "name": "number",
                        "type": "AMAZON.NUMBER"
                    }
                ],
                "samples": [
                    "{number}",
                    "is it {number}",
                    "how about {number}",
                    "could be {number}"
                ]
            }
        ],
        "types": []
    }
}

**Comment by franklin-lobb** [comment]
The model file has been updated to the latest schema and tested.  Are you still experiencing this issue?
