### ISSUE TITLE
alternate index.js for use with local https server using node/express

### ISSUE THREAD

**Issue by johngo7470** [alexa/skill-sample-nodejs-highlowgame#29]
For those who want to run the high-low skill on your own https (Node.js) server, I've attached a version of index.js (highlowApp.js) wrapped with express (for testing purposes only - no Skill ID check). 

[highlowApp.js.txt](https://github.com/alexa/skill-sample-nodejs-highlowgame/files/1756483/highlowApp.js.txt)

**Comment by franklin-lobb** [comment]
Thanks for supplying the sample.  I'm closing the issue (since it's not an issue per se).
