### ISSUE TITLE
I may be missing something simple...

### ISSUE THREAD

**Issue by tonysmall** [alexa/skill-sample-nodejs-highlowgame#3]
I'm new-ish to Alexa skills, and I can't get past the first line.  Here's the error I get on this line "var Alexa = require("alexa-sdk");".  Am I don't something wrong?  Or is there some configuration setting I need to do?

{
  "errorMessage": "Cannot find module 'alexa-sdk'",
  "errorType": "Error",
  "stackTrace": [
    "Object.<anonymous> (/var/task/index.js:2:13)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}

**Comment by trayo** [comment]
I think you need to install the alexa-sdk node package. Install instructions are [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#installing-and-working-with-the-alexa-skills-kit-sdk-for-nodejs-alexa-sdk).

**Comment by nish17** [comment]
@trayo What if this type of error occurs during testing on lambda console?

**Comment by akersh-s** [comment]
@nish17 It means you're missing the SDK. Either start from the alexa-skills-fact blueprint (https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/instructions/2-lambda-function.md on Step 5), or if you're zip uploading to Lambda, make sure that node_modules are included.

Marking this issue as closed.
