### ISSUE TITLE
error calling lambda function

### ISSUE THREAD

**Issue by fluxquantum** [alexa/skill-sample-nodejs-highlowgame#34]
Hello I am seeing the following error:

Syntax error in module 'index': SyntaxError
async handle(handlerInput) {
^^^^^^
SyntaxError: Unexpected identifier

Is there another dependency I need to add?

**Comment by simbas** [comment]
Could you give more contextual information please? Node.js version?

**Comment by franklin-lobb** [comment]
Depending on how you created your lambda function, it may have defaulted to Node 6.10.  Async requires Node 8.10.  From your lambda function in the AWS console, change the runtime and choose save.

**Comment by fluxquantum** [comment]
I'm using Node.js version 6.10. I had a similar issue with the await function.

**Comment by jimshalo10** [comment]
@fluxquantum  see my pull request https://github.com/alexa/skill-sample-nodejs-highlowgame/pull/35
The orignal lambda/custom/package.json was using node 6.1 now updated to use 8.1 which clears the Lambda exectuion symbol error "keyword "async" not recognised line 19 async handle(" in Cloud watch logs
Issue #, if available:
Description of changes:
Changed dependencies to
"dependencies": {
"ask-sdk-core": "^2.0.0",
"ask-sdk-model": "^1.0.0"
}
In index.js line 5 change 
const Alexa = require('ask-sdk');
to 
const Alexa = require('ask-sdk-core');

**Comment by jimshalo10** [comment]
Well this applied latest pull request to my fork and in the Alexa Developer console Test box
with the following Alexa test command , which starts the game until complete and the counter updated during the session is shown when you start another game. 
Finally you must type the word "twenty" not use the number 20 or you get an error saying did not understand command. "one", seventy, eleven are all valid. 1,70,11 are all invalid

**tell high low game "10"**

**Comment by franklin-lobb** [comment]
It's not clear to me if there's still an open issue here.  The requirement to type the numbers out (twenty vs. 20) is how the simulator works.  I agree it would be nice to not require that.  You can upvote that feature request at [alexa.uservoice.com](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/36277477-in-the-test-simulator-accept-numbers-as-digits-n).

If there is still an issue, please re-open on open a new issue with the details of the error/problem.  Thanks!
