### ISSUE TITLE
Cannot find module ask-sdk

### ISSUE THREAD

**Issue by harrykrisgit** [alexa/skill-sample-nodejs-highlowgame#39]
I followed the instructions to create the lambda function using the blueprint "alexa-skill-kit-sdk-factskill".
When I test my lambda function (Start Session), I get the error "Cannot find module ask-sdk". 
I have also attached package.json screen print. Appreciate any pointers for this issue.

<img width="539" alt="capture" src="https://user-images.githubusercontent.com/29766420/46780319-e3170280-ccd0-11e8-9e72-266d0a4f8907.PNG">

{
  "errorMessage": "Cannot find module 'ask-sdk'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "Object.<anonymous> (/var/task/index.js:5:15)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)"
  ]
}

**Comment by harrykrisgit** [comment]
I tried ask CLI instructions provided and that seemed to install the required ask-sdk module.

**Comment by gcnes** [comment]
Yes just go back and download everything again using ask-cli.

**Comment by govindpn** [comment]
use the below import
const Alexa = require('ask-sdk-core');
instead of 
const Alexa = require('ask-sdk');
