### ISSUE TITLE
Error when hosted as a webservice

### ISSUE THREAD

**Issue by SomaSharathSurya** [alexa/skill-sample-nodejs-highlowgame#4]
Hi 

I am getting following error when testing in the service emulator  "**_There was an error calling the remote endpoint, which returned HTTP 405 : Method Not Allowed_**".  I have just cloned this code and hosted it as a webservice in azure by updating my app id in the code. Does this code work only with lambda function or it works anywher? 

Please help !

**Comment by rob94p** [comment]
you need to just comment out this: 

```
exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.appId = appId;
    //alexa.dynamoDBTableName = 'highLowGuessUsers';
    alexa.registerHandlers(newSessionHandlers, guessModeHandlers, startGameHandlers, guessAttemptHandlers);
    alexa.execute();
};
```

**Comment by akersh-s** [comment]
Thanks @rob94p -- marking this issue a closed.
