### ISSUE TITLE
Syntax error in context.json at position 3 / or assume role issue

### ISSUE THREAD

**Issue by danagibson** [alexa/skill-sample-nodejs-highlowgame#8]
I'm getting an error thrown: Syntax error in context.json at position 3.

Is there something that has changed in the context file...or syntax change?
Since this doesn't seem to be associated with what I opened it under....I'm using the local debugging from https://developer.amazon.com/blogs/alexa/post/Tx24Z2QZP5RRTG1/new-alexa-technical-tutorial-debugging-aws-lambda-code-locally

Can someone help?

**Comment by JennJin** [comment]
I think this has been resolved since the example no longer has a context.json. If not, please reopen with which file is having an issue.
